[project]
name = "advent-code"
version = "0.1.0"
description = "Me trying to solve some advent code event tasks"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy>=2.1.3",
    "pandas>=2.2.3",
]
